####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CFLAGS = -g -O2 -Wall -D_XSOCK_USE_SSL -I./src
LIBS = -lssl -lcrypto
NAME = statcov
ODIR = obj
OBJ = o

OBJS = version.$(OBJ) \
	nbg.$(OBJ) \
	sock.$(OBJ) \
	statcov.$(OBJ) \
	http.$(OBJ) \
	covid.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
INSTALL = /usr/bin
VPATH = ./src

.c.$(OBJ):
	@test -d $(ODIR) || mkdir $(ODIR)
	$(CC) $(CFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(CC) $(CFLAGS) -o $(ODIR)/$(NAME) $(OBJECTS) $(LIBS)

.PHONY: install
install:
	@test -d $(INSTALL) || mkdir $(INSTALL)
	@install -m 0755 $(ODIR)/$(NAME) $(INSTALL)/

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
